### ISSUE TITLE
[Solved][Q&A] ¿Is possible to bind single bone to different layers or bone chain?

### ISSUE THREAD

**Issue by Jose-Moreno** [hidefuku/AnimeEffects#13]
@hidefuku @henrich Hi! I want to congratulate you on your tool AnimeEffects. It is very well done and so far very promising!.

I wanted to ask if it's possible to do the following operations in your program:

1) To have one bone to be the parent of (X) number of individual layers. That means having any bone I choose to directly influence any layer. Also for a bone chain to influence a hierarchy of layers.

I've tried to use the current bone tool with a folder that has the artwork nested inside with other folders and it works OK, but with this method all the images are deformed by the other bones.  The problem is that I want each layer transformation property (rotation, move, scale) to be modified only by a single bone, disregarding any other bone influence over the same image.

For example if I have an ARM made of three (3) pieces in different layers. ARM > FOREARM > HAND. I want to have a bone chain that allow me to manipulate these layers separately, that means one bone would only influence a single layer each.

2) Is it possible to bind one bone from **layer A** to other bone in **layer B** so one bone can become parent of the other in a different layer? This would help to create complex binding between many layers joining chains of bones into a single skeleton.

Example. I have the same ARM with a three (3) bone chain in layer A, and on layer B I have a body where I created a SHOULDER bone. I would like to parent the arm root joint to the shoulder bone to allow for the shoulder bone to move the whole arm.

Thank you for your hard work on this excellent program. I'd like to help out but I don't know how to code in C++ & QT :sob: however If there's something I can help with, like testing the program or promoting the site let me know.

I'm a freelance animator and I'd love to recommend this software to my colleagues so I'm excited to see how this software will evolve :smile: Thanks!!!

**Comment by hidefuku** [comment]
If you are using version 1.3.0 or lower, please update to 1.3.4.

Question 1
Yes. Please read the document "Bind Objects".
http://animeeffects.org/doc/v1.3/en/tooldock.html#bone-creating-tool

Question 2
Partially yes. You can create nested bone chains within a bound object.

**Comment by Jose-Moreno** [comment]
@hidefuku Thanks a lot for your answer! I didn't know there was a documentation page oops, I'll make sure to read it right away :smile: 

I will close this issue to keep the tracker clean, but I'll make some tests for these cases later and share them here so others looking for similar answers can benefit from it :+1: 

I'll also keep sharing news about the software on twitter, let's hope more people become interested in AnimeEffects! :smile:
