### ISSUE TITLE
Proper Documentation

### ISSUE THREAD

**Issue by DefinitelyaLeo** [hidefuku/AnimeEffects#23]
As far as I am concerned I am unable to use this, as I'm not sure what it does. There is no function to import images, there is no project file that shows the functionality. I open the software and there is just a set of tools and no options to do anything else.

**Comment by DefinitelyaLeo** [comment]
I found videos posted on youtube, you should probably add the links in the github pages so person interested have those as a starting point

**Comment by Jose-Moreno** [comment]
@DefinitelyaLeo Just in case you or anyone else can't find it, these are the user docs for AnimeEffects http://animeeffects.org/doc/v1.3/en/index.html

**Comment by DefinitelyaLeo** [comment]
@Jose-Moreno Thanks I did find it but there is also videos showing the functionalities that are on youtube that could be posted here or the main website. I was a bit lost until I found the videos.
