### ISSUE TITLE
helpwith building AnimeEffects on manjaro linux

### ISSUE THREAD

**Issue by blurymind** [hidefuku/AnimeEffects#42]
Opening it in qt creator, and then building seems to go smoothy, however when I try to start it with ./AnimeEffects in the src folder, I get this
![Screenshot_2020-05-05_17-19-03](https://user-images.githubusercontent.com/6495061/81082981-e5146800-8eeb-11ea-956e-0d525cc81b34.png)

if I move the AnimeEffects file to the parent folder, it does work! But why is it building it inside src?

I am new to qt creator, when I try the build and run command, it doesnt start at all. I get this:
`:-1: error: You need to set an executable in the custom run configuration.`
However the option to do so is impossible to find. Where  is it? 
These are my settings atm:
![Screenshot_2020-05-05_17-22-29](https://user-images.githubusercontent.com/6495061/81083219-33c20200-8eec-11ea-97cd-4412e473862d.png)

**Comment by azagaya** [comment]
@blurymind would you send a picture of what the project tab in Qt Creator says? Mine is this:
![imagen](https://user-images.githubusercontent.com/46932830/81087298-ea63b980-8ecf-11ea-9fb2-e1b6e206c1e0.png)
Perhaps your build directory is not properly set.

**Comment by blurymind** [comment]
After restarting my project this field became populated, it wasnt before.

Now I was able to fix both of my issues with these settings:

![Screenshot_2020-05-05_18-11-45](https://user-images.githubusercontent.com/6495061/81088655-29573680-8ef3-11ea-85c4-1afedbb32eac.png)

Do they look right to you? It builds properly now and playtests really fast!

Do you guys know if we have any testing files to experiment with while playing with the code?

**Comment by azagaya** [comment]
@blurymind the picture i show you before was automatically populated by Qt. I dont know why it made different configuration on your system. What i see there is basically buildin the binary in the root dir of the repo. In my configuration, it creates another folder where it builds.

About testing files, you mean something like a testing project?

**Comment by blurymind** [comment]
> @blurymind the picture i show you before was automatically populated by Qt. I dont know why it made different configuration on your system. What i see there is basically buildin the binary in the root dir of the repo. In my configuration, it creates another folder where it builds.
> 
> About testing files, you mean something like a testing project?

yeah a testing project file that can be opened in the app would be amazing to have

**Comment by blurymind** [comment]
something like
https://github.com/DragonBones/Demos

would help attract devs

anyways, closing this now
