### ISSUE TITLE
AnimeEffects Goes Blank

### ISSUE THREAD

**Issue by asiastarryfish** [hidefuku/AnimeEffects#44]
Hello! Every time I finish extracting the files and putting ffmeg under the files, that works just fine. But when I click to open the bunny icon (the application), it goes to a blank screen before closing out. I went through over the course of 2 days, checking to see if I have all the requirements and checking GitHub for solutions. I already ran it as an administrator, troubleshoot, and went through the requirements and files needed to download. 
![blank](https://user-images.githubusercontent.com/71446363/93477299-dcd02e80-f8c8-11ea-8d7a-a13b42827477.png) I have a 64bit Windows with enough RAM, and WinRAR. Is there anything I can do?

**Comment by DkOkami** [comment]
same problem here

**Comment by asiastarryfish** [comment]
I had this problem a while back, but Animeeffects works fine now. I waited a couple of weeks and updated my drivers/P.C. I don't use the program anymore since it's kinda amateur.
